# Generated by Django 3.2.13 on 2022-07-14 07:07

from django.db import migrations, models
import django.utils.timezone
import shortcode.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortCode',
            fields=[
                ('shortcode', models.CharField(default=shortcode.utils.generate_shortcode, help_text='lowercase short url. Automatically allocated shortcodes are exactly 6-length. User subitted shortcodes are at leat 4-length.', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Short URL')),
                ('original_url', models.CharField(help_text='Original long URL', max_length=255, verbose_name='Original URL')),
                ('access_count', models.PositiveIntegerField(default=0, editable=False, help_text='How many times this short code is accessed', verbose_name='Access Count')),
                ('last_accessed_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when the shortcode was last accessed', null=True, verbose_name='Last Accessed')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created. The date and time are displayed in the Timezone from where request is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC', verbose_name='Registered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was modified. The date and time are displayed in the Timezone from where request is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC', null=True, verbose_name='Updated')),
            ],
        ),
    ]
