"""
Django settings for project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "js9&8)s2ljizr6ku19#)@xp1!jl^r3p0z^0op@rdjjfy=*e29s"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "shortcode",
    "drf_yasg",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = "/static/"

API_VERSION = 1

SHORTCODE_MAX_LENGTH = 20

SWAGGER_SETTINGS = {
    "SUPPORTED_SUBMIT_METHODS": [  # Specify which methods to enable in Swagger UI
        "get",
        "post",
        "put",
        "patch",
        "destroy",
        "head",
        "delete",
    ],
    "SECURITY_DEFINITIONS": {
        # 'basic': {
        #     'type': 'basic'
        # },
    },
    # 'LOGIN_URL': reverse_lazy('login'),
    # 'LOGOUT_URL': reverse_lazy('logout'),
    "USE_SESSION_AUTH": False,
    "JSON_EDITOR": True,
    "DOC_EXPANSION": "none",  # ["list"*, "full", "none"]
    "REFETCH_SCHEMA_ON_LOGOUT": True,
    "SHOW_REQUEST_HEADERS": True,
    "APIS_SORTER": "alpha",
    "DEFAULT_MODEL_DEPTH": 3,  # -1
    "DEFAULT_MODEL_RENDERING": "example",
    "OPERATIONS_SORTER": "none",  # [alpha, method, none],
    "DEEP_LINKING": True,
    "REQUIRED_PROPS_FIRST": False,
    "DISPLAY_OPERATION_ID": True,
    "PERSIST_AUTHORIZATION": True,
    # 'SUPPORTED_SUBMIT_METHODS': "[\"get\", \"post\"]",
    "TRY_IT_OUT_ENABLED": True,
    "FILTER": True,
    "WITH_CREDENTIALS": True,
    "PERSIST_AUTHORIZATION": True,
    "DEFAULT_INFO": "config.admin_api_urls",
    "COMPONENT_SPLIT_REQUEST": True,
    "HIDE_HOSTNAME": True,
    "PATH_IN_MIDDLE": True,
}

REDOC_SETTINGS = {
    "LAZY_RENDERING": True, 
    "PATH_IN_MIDDLE": True
}
